# Generated by Django 5.2.8 on 2025-11-24 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats_api', '0002_evaluation_alter_evaluationpair_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='prenom',
        ),
    ]
