# Generated by Django 5.2.8 on 2025-11-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_api', '0003_remove_candidat_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
