# Generated by Django 5.2.8 on 2025-11-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_api', '0004_joboffer_company_name_joboffer_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='type_de_contrat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
