# Generated by Django 5.2.8 on 2025-11-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats_api', '0005_joboffer_type_de_contrat'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='fingerprint',
            field=models.CharField(max_length=32, null=True, unique=True),
        ),
    ]
